### ISSUE TITLE
Xamarin.Forms Android: Specified cast is not valid, only in V2.0.0

### ISSUE THREAD

**Issue by ilexius** [xamarin/SignaturePad#65]
Hi,
first, thanks for this amazing component!!!

I'm trying to use version 2.0.0, but get the error in the stack trace below. Using version 1.5.1 it is working fine. I have installed the Forms component in my PCL and Android project.

```
05-07 19:51:23.599 I/MonoDroid(11334): System.InvalidCastException: Specified cast is not valid.
05-07 19:51:23.599 I/MonoDroid(11334):   at (wrapper castclass) System.Object:__castclass_with_cache (object,intptr,intptr)
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Registrar`1[TRegistrable].GetHandler (System.Type type) [0x0001b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Registrar.cs:24 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Registrar`1[TRegistrable].GetHandler[TOut] (System.Type type) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Registrar.cs:29 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00006] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:288 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00023] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:84 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00104] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:217 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:68 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:335 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00111] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:199 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:137 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x0001f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00023] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:84 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00104] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:217 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:68 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:335 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00111] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:199 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:137 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x0001f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x00023] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:84 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00104] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:217 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:68 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:335 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00111] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:199 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:137 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x0001f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.AppCompat.Platform+ModalContainer..ctor (Android.Content.Context context, Xamarin.Forms.Page modal) [0x00038] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:335 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.PresentModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x0000d] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:285 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Platform.Android.AppCompat.Platform+<Xamarin-Forms-INavigation-PushModalAsync>d__30.MoveNext () [0x0004a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:150 
05-07 19:51:23.599 I/MonoDroid(11334): --- End of stack trace from previous location where exception was thrown ---
05-07 19:51:23.599 I/MonoDroid(11334):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
05-07 19:51:23.599 I/MonoDroid(11334):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
05-07 19:51:23.599 I/MonoDroid(11334):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
05-07 19:51:23.599 I/MonoDroid(11334):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
05-07 19:51:23.599 I/MonoDroid(11334):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
05-07 19:51:23.599 I/MonoDroid(11334):   at Xamarin.Forms.Application+NavigationImpl+<OnPushModal>d__3.MoveNext () [0x0008d] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Application.cs:338 
05-07 19:51:23.599 I/MonoDroid(11334): --- End of stack trace from previous location where exception was thrown ---
```

**Comment by brendonpaul** [comment]
Clarification - switching to 1.5.1 did work after cleaning and rebuilding the project.... :-)

**Comment by mattleibow** [comment]
@brendonpaul If you switch back to v2.0 and then delete all the `bin` and `obj` folders, does that fix issues. There may be some issue with the fast-deploy mechanism that is not properly cleaning out the app on the device.

**Comment by brendonpaul** [comment]
Hi Matthew,

I'm out of town for a couple of days, but will give it a try as soon as I'm
back in front of my machine and report back.

Brendon

On May 24, 2017 9:02 PM, "Matthew Leibowitz" <notifications@github.com>
wrote:

@brendonpaul <https://github.com/brendonpaul> If you switch back to v2.0
and then delete all the bin and obj folders, does that fix issues. There
may be some issue with the fast-deploy mechanism that is not properly
cleaning out the app on the device.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xamarin/SignaturePad/issues/65#issuecomment-303893935>,
or mute the thread

**Comment by brendonpaul** [comment]
Hi Mathew,

 

That seemed to do the trick – many thanks for your help,

 

Cheers,

 

Brendon

 

 

 

Brendon Paul

Ixiom Software Inc.

 

Phone:  1-519-957-1760 x 501

Cell: 1-519-729-6255

Fax:  1-888-597-2495


This message may contain confidential or privileged information and is intended only for the use of the individual or entity to which it is addressed. 
If you have received this email message in error, or are not the named addressee, please notify the sender and permanently delete this message. 
Any sharing or use of the information contained in this message or attached to this message, by persons other than the intended recipient, is prohibited

**Comment by ainsophical** [comment]
i ran into the same problem. re-installing nuget and del'ing bin/obj cross plat worked for me with this error...

**Comment by capraynor** [comment]
I also ran into the same problem. 1.5.1 can work properly, but this error still occur when switching to 2.0+
